#!/bin/sh

#. /lib/lsb/init-functions

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
START_IN=/opt/replad
#START_IN=~/Projects/pers/replad
SCRIPT=server.js
USER=root
CONFIG_FILE=/etc/adproxy.conf
FOREVER_HOME=/var/cache/adproxy

case "$1" in
  start)
    cd $START_IN
    forever start -p $FOREVER_HOME -a -l /dev/null  $SCRIPT -f easylist.txt
    ;;
  stop)
    cd $START_IN
    forever stop -p $FOREVER_HOME $SCRIPT
    ;;
  restart)
    $0 stop
    $0 start
    ;;
esac

